[package]
name = "git-diary"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "^1.0.95"
async-openai = "^0.27.2"
async-trait = "0.1.77"
chrono = "^0.4.39"
git2 = "^0.20.0"
mockall = "0.11.4"
tempfile = "3.8.1"
tokio = { version = "^1.43.0", features = ["full"] }
